on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: ['windows-latest','ubuntu-latest']
        dotnet-version: ['3.1.201']
        project : ['Json-Rpc']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{matrix.dotnet-version}}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ${{matrix.project}} --configuration Release
      - name: Test
        run: dotnet test AustinHarris.JsonRpcTestN 
