on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: ['ubuntu-latest']
#        dotnet-version : ['3.1.102','3.1.201']
        dotnet-framework : ['netcoreapp3.1']
        project : ['Json-Rpc']
#       runtime: ['ubuntu.16.04-x64']
#        include:
#          - os: windows-latest
#            dotnet-version : '4.7.2'
#            dotnet-framework : 'net40'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{matrix.dotnet-version}}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ${{matrix.project}} -f ${{matrix.dotnet-framework}} --configuration Release
      - name: Test
        run: dotnet test AustinHarris.JsonRpcTestN --verbosity normal
