on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: ['windows-latest','ubuntu-latest']
        dotnet-version: ['3.1.201']
        project : ['Json-Rpc']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{matrix.dotnet-version}}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ${{matrix.project}} --configuration Release
      - name: Test
        run: dotnet test AustinHarris.JsonRpcTestN 
      # Publish
      - name: publish nuget version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Json-Rpc/AustinHarris.JsonRpc.csproj # Relative to repository root
          PACKAGE_NAME: NuGet package id, REQUIRED if it's different from project name
          # VERSION_FILE_PATH: Directory.Build.props # Relative to repository root, defaults to project file
          # VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          # VERSION_STATIC: Static version, useful for external providers like Nerdbank.GitVersioning
          TAG_COMMIT: true # Flag to enable / disable git tagging
          TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NugetKey}} # API key for the NuGet feed
